[workspace]

members = [
    "discovery_parser",
    "google_field_selector",
    "google_field_selector_derive",
    "google_rest_api_generator",
    "uri_template_parser",
    "shared",
    "mcp",
]
