[package]
name = "discovery_parser"
version = "0.1.0"
authors = ["Glenn Griffin <ggriffiniii@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
reqwest = "0.9.18"
serde_json = "1"
